import { routerRedux } from 'dva/router';


export default {
  namespace: 'sharedResource',
  state: {
    data: [
      {
        id: '1',
        title: '人口普查信息',
        subject: '市场监管',
        rate: 2,
        key: '',
        authStatus: true,
        source: '自治区住建厅',
        dataFormat: '库表 文件 接口',
        sharedType: '有条件共享',
        openType: '不向社会开放',
        visitNum: 32,
        applyNum: 14,
        dataNum: 232,
        fileNum: 4,
        publishTime: '2018-07-04',
        updateFrequency: '每年',
        updateTime: '2018-07-04',
        star: false,
        description: '关于人口普查信息',
        useCondition: {
          downloadNum: 5,
          ratePNum: 5,
          rateTNum: 3,
          rateNum: 5,
          rate: 2,
        },
        messageLength: 23,
        dataItem: [
          {name: '统一社会信用代码', format: '字符串型C', description: '统一社会信用代码'},
          {name: '主体名称', format: '字符串型C', description: '主体名称'},
          {name: '住所（经营场所）', format: '字符串型C', description: '住所（经营场所）'},
          {name: '经营者', format: '字符串型C', description: '经营者'},
          {name: '经营范围', format: '字符串型C', description: '经营范围'},
          {name: '经营期限起', format: '字符串型C', description: '经营期限起'},
          {name: '经营期限至', format: '字符串型C', description: '经营期限至'},
          {name: '成立日期', format: '字符串型C', description: '成立日期'},
        ],
        dataDetail: [
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
        ],
        folders: [{},{}],
        files: [
          { name: '大屏背景地球图.png', contentType: 'png', source: '网站上传', publishTime: '2018-09-09 12:21:25', size: '351kb', url: '/assets/地球.png'},
          { name: '自治区政务信息升级维护.pdf', contentType: 'pdf', source: '网站上传', publishTime: '2018-09-09 12:21:23', size: '321kb', url: '/documents/自治区政务信息共享网站建设和政务信息共享与交换平台升级维护FV.pdf'},
          { name: '地质灾害易发区.docx', contentType: 'docx', source: '网站上传', publishTime: '2018-09-09 12:21:25', size: '351kb', url: 'https://view.officeapps.live.com/op/view.aspx?src=newteach.pbworks.com%2Ff%2Fele%2Bnewsletter.docx'}
        ],
        messages: [
          {id: '1', user: '2018L', createTime: '2018-09-11 20:10:22', content: '好评！'},
          {id: '2', user: '2018YYY', createTime: '2018-09-12 18:10:22', content: '好评!!!!!!!!!!!!!!!!!!!！'},
        ],
      },
      {
        id: '2',
        title: '软件企业认定证书',
        subject: '软件企业认定证书',
        rate: 2,
        key: '',
        authStatus: true,
        source: '自治区经信委',
        dataFormat: '库表 文件 接口',
        sharedType: '有条件共享',
        openType: '不向社会开放',
        visitNum: 32,
        applyNum: 14,
        dataNum: 232,
        fileNum: 4,
        publishTime: '2018-07-04',
        updateFrequency: '每年',
        updateTime: '2018-07-04',
        star: false,
        description: '有效期，注册地址，注册日期，颁证时间，持证者，发证机关，证照编号，工商注册号，企业名称，身份证号码',
        useCondition: {
          downloadNum: 5,
          ratePNum: 5,
          rateTNum: 3,
          rateNum: 5,
          rate: 2,
        },
        messageLength: 23,
        dataItem: [
          {name: '统一社会信用代码', format: '字符串型C', description: '统一社会信用代码'},
          {name: '主体名称', format: '字符串型C', description: '主体名称'},
          {name: '住所（经营场所）', format: '字符串型C', description: '住所（经营场所）'},
          {name: '经营者', format: '字符串型C', description: '经营者'},
          {name: '经营范围', format: '字符串型C', description: '经营范围'},
          {name: '经营期限起', format: '字符串型C', description: '经营期限起'},
          {name: '经营期限至', format: '字符串型C', description: '经营期限至'},
          {name: '成立日期', format: '字符串型C', description: '成立日期'},
        ],
        dataDetail: [
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
        ],
        interface: {
          url: '/sjw/gjxlmccxgjxlxx/1.3发分区信息',
          requestParams: [
            {name: 'ifkey', type: '字符串', require: '必填', description: '接口标识'},
            {name: 'query1', type: '字符串', require: '必填', description: '报表名称'},
            {name: 'query2', type: '字符串', require: '必填', description: '报表期别'},
            {name: 'tablename', type: '字符串', require: '必填', description: '业务数据实体表名'},
            {name: 'checkstr', type: '字符串', require: '必填', description: '有关部门提供的有效8位数校验码'},
          ],
          returnParams: [
            {name: 'set', description: '站点设置'},
            {name: 'type', description: '站点类型'},
            {name: 'run', description: '运行方向'},
          ],
          statusCode: [
            {code: '200', description: '请求成功'},
            {code: '201', description: '接口标识不正确'},
            {code: '202', description: '接口识别码不正确'},
            {code: '203', description: '无相关数据'},
            {code: '204', description: '当日查询字段超出'},
            {code: '205', description: '查询失败，请联系管理员'},
          ],
        },
        messages: [
          {id: '1', user: '2018L', createTime: '2018-09-11 20:10:22', content: '好评！'},
          {id: '2', user: '2018YYY', createTime: '2018-09-12 18:10:22', content: '好评!!!!!!!!!!!!!!!!!!!！'},
        ],
      },
      {
        id: '21',
        title: '数字线划图（地形图）',
        subject: '矢量数据集 地形图',
        rate: 2,
        key: '',
        authStatus: true,
        source: '自治区测绘局',
        dataFormat: '库表 文件 接口',
        sharedType: '有条件共享',
        openType: '不向社会开放',
        visitNum: 32,
        applyNum: 14,
        dataNum: 232,
        fileNum: 4,
        publishTime: '2018-07-04',
        updateFrequency: '每年',
        updateTime: '2018-07-04',
        star: false,
        description: '数字线划图是现有地形图要素的矢量数据集，保存各要素间的空间关系和相关的属性信息，全面地描述地表目标。',
        useCondition: {
          downloadNum: 5,
          ratePNum: 5,
          rateTNum: 3,
          rateNum: 5,
          rate: 2,
        },
        messageLength: 23,
        dataItem: [
          {name: '统一社会信用代码', format: '字符串型C', description: '统一社会信用代码'},
          {name: '主体名称', format: '字符串型C', description: '主体名称'},
          {name: '住所（经营场所）', format: '字符串型C', description: '住所（经营场所）'},
          {name: '经营者', format: '字符串型C', description: '经营者'},
          {name: '经营范围', format: '字符串型C', description: '经营范围'},
          {name: '经营期限起', format: '字符串型C', description: '经营期限起'},
          {name: '经营期限至', format: '字符串型C', description: '经营期限至'},
          {name: '成立日期', format: '字符串型C', description: '成立日期'},
        ],
        dataDetail: [
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
        ],
        interface: {
          url: '/sjw/gjxlmccxgjxlxx/1.3发分区信息',
          requestParams: [
            {name: 'ifkey', type: '字符串', require: '必填', description: '接口标识'},
            {name: 'query1', type: '字符串', require: '必填', description: '报表名称'},
            {name: 'query2', type: '字符串', require: '必填', description: '报表期别'},
            {name: 'tablename', type: '字符串', require: '必填', description: '业务数据实体表名'},
            {name: 'checkstr', type: '字符串', require: '必填', description: '有关部门提供的有效8位数校验码'},
          ],
          returnParams: [
            {name: 'set', description: '站点设置'},
            {name: 'type', description: '站点类型'},
            {name: 'run', description: '运行方向'},
          ],
          statusCode: [
            {code: '200', description: '请求成功'},
            {code: '201', description: '接口标识不正确'},
            {code: '202', description: '接口识别码不正确'},
            {code: '203', description: '无相关数据'},
            {code: '204', description: '当日查询字段超出'},
            {code: '205', description: '查询失败，请联系管理员'},
          ],
        },
        messages: [
          {id: '1', user: '2018L', createTime: '2018-09-11 20:10:22', content: '好评！'},
          {id: '2', user: '2018YYY', createTime: '2018-09-12 18:10:22', content: '好评!!!!!!!!!!!!!!!!!!!！'},
        ],
      },
      {
        id: '22',
        title: '事业单位登记信息',
        subject: '事业单位',
        rate: 2,
        key: '',
        authStatus: true,
        source: '自治区质监局',
        dataFormat: '库表 文件 接口',
        sharedType: '有条件共享',
        openType: '不向社会开放',
        visitNum: 32,
        applyNum: 14,
        dataNum: 232,
        fileNum: 4,
        publishTime: '2018-07-04',
        updateFrequency: '每年',
        updateTime: '2018-07-04',
        star: false,
        description: '机构名称，法定代表人，注册日期',
        useCondition: {
          downloadNum: 5,
          ratePNum: 5,
          rateTNum: 3,
          rateNum: 5,
          rate: 2,
        },
        messageLength: 23,
        dataItem: [
          {name: '统一社会信用代码', format: '字符串型C', description: '统一社会信用代码'},
          {name: '主体名称', format: '字符串型C', description: '主体名称'},
          {name: '住所（经营场所）', format: '字符串型C', description: '住所（经营场所）'},
          {name: '经营者', format: '字符串型C', description: '经营者'},
          {name: '经营范围', format: '字符串型C', description: '经营范围'},
          {name: '经营期限起', format: '字符串型C', description: '经营期限起'},
          {name: '经营期限至', format: '字符串型C', description: '经营期限至'},
          {name: '成立日期', format: '字符串型C', description: '成立日期'},
        ],
        dataDetail: [
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
        ],
        interface: {
          url: '/sjw/gjxlmccxgjxlxx/1.3发分区信息',
          requestParams: [
            {name: 'ifkey', type: '字符串', require: '必填', description: '接口标识'},
            {name: 'query1', type: '字符串', require: '必填', description: '报表名称'},
            {name: 'query2', type: '字符串', require: '必填', description: '报表期别'},
            {name: 'tablename', type: '字符串', require: '必填', description: '业务数据实体表名'},
            {name: 'checkstr', type: '字符串', require: '必填', description: '有关部门提供的有效8位数校验码'},
          ],
          returnParams: [
            {name: 'set', description: '站点设置'},
            {name: 'type', description: '站点类型'},
            {name: 'run', description: '运行方向'},
          ],
          statusCode: [
            {code: '200', description: '请求成功'},
            {code: '201', description: '接口标识不正确'},
            {code: '202', description: '接口识别码不正确'},
            {code: '203', description: '无相关数据'},
            {code: '204', description: '当日查询字段超出'},
            {code: '205', description: '查询失败，请联系管理员'},
          ],
        },
        messages: [
          {id: '1', user: '2018L', createTime: '2018-09-11 20:10:22', content: '好评！'},
          {id: '2', user: '2018YYY', createTime: '2018-09-12 18:10:22', content: '好评!!!!!!!!!!!!!!!!!!!！'},
        ],
      },
      {
        id: '3',
        title: '地质灾害易发分区信息',
        subject: '市场监管，信用服务',
        rate: 2,
        key: '',
        authStatus: true,
        source: '自治区住建厅',
        dataFormat: '库表 文件 接口',
        sharedType: '有条件共享',
        openType: '不向社会开放',
        visitNum: 32,
        applyNum: 14,
        dataNum: 232,
        fileNum: 4,
        publishTime: '2018-07-04',
        updateFrequency: '每年',
        updateTime: '2018-07-04',
        star: false,
        description: '关于地质灾害易发分区信息',
        useCondition: {
          downloadNum: 5,
          ratePNum: 5,
          rateTNum: 3,
          rateNum: 5,
          rate: 2,
        },
        messageLength: 23,
        dataItem: [
          {name: '统一社会信用代码', format: '字符串型C', description: '统一社会信用代码'},
          {name: '主体名称', format: '字符串型C', description: '主体名称'},
          {name: '住所（经营场所）', format: '字符串型C', description: '住所（经营场所）'},
          {name: '经营者', format: '字符串型C', description: '经营者'},
          {name: '经营范围', format: '字符串型C', description: '经营范围'},
          {name: '经营期限起', format: '字符串型C', description: '经营期限起'},
          {name: '经营期限至', format: '字符串型C', description: '经营期限至'},
          {name: '成立日期', format: '字符串型C', description: '成立日期'},
        ],
        dataDetail: [
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
        ],
        database: {
          host: '10.103.321.78',
          post: '8080',
          code: 'neoda_21_NOVA',
          userName: 'test',
          password: '123456',
          tables: [
            {key: '1', tableName: '自治区国土局地质灾害易发分区信息_1',
              fields: [
                {name: 'id', label: '主键1', description: '无', type: '长整型', size: '18', ifKey: '是', ifNull: '是'},
                {name: 'code', label: '地方基本编码', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code1', label: '地方基本编码1', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code2', label: '地方基本编码2', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code3', label: '地方基本编码3', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code4', label: '地方基本编码4', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code5', label: '地方基本编码5', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code6', label: '地方基本编码6', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code7', label: '地方基本编码7', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code8', label: '地方基本编码8', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code9', label: '地方基本编码9', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
                {name: 'code10', label: '地方基本编码10', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'},
              ],
              preview: [
                {id: 'key1', code: 'YUI', code1: 'PPP', code2: 'PPP', code3: 'PPP', code4: 'PPP', code5: 'PPP', code6: 'PPP', code7: 'PPP', code8: 'PPP', code9: 'PPP', code10: 'PPP'},
                {id: 'key2', code: 'YUI', code1: 'PPP', code2: 'PPP', code3: 'PPP', code4: 'PPP', code5: 'PPP', code6: 'PPP', code7: 'PPP', code8: 'PPP', code9: 'PPP', code10: 'PPP'},
                {id: 'key3', code: 'YUI', code1: 'PPP', code2: 'PPP', code3: 'PPP', code4: 'PPP', code5: 'PPP', code6: 'PPP', code7: 'PPP', code8: 'PPP', code9: 'PPP', code10: 'PPP'},
                {id: 'key4', code: 'YUI', code1: 'PPP', code2: 'PPP', code3: 'PPP', code4: 'PPP', code5: 'PPP', code6: 'PPP', code7: 'PPP', code8: 'PPP', code9: 'PPP', code10: 'PPP'},
                {id: 'key5', code: 'YUI', code1: 'PPP', code2: 'PPP', code3: 'PPP', code4: 'PPP', code5: 'PPP', code6: 'PPP', code7: 'PPP', code8: 'PPP', code9: 'PPP', code10: 'PPP'},
                {id: 'key6', code: 'YUI', code1: 'PPP', code2: 'PPP', code3: 'PPP', code4: 'PPP', code5: 'PPP', code6: 'PPP', code7: 'PPP', code8: 'PPP', code9: 'PPP', code10: 'PPP'},
                {id: 'key7', code: 'YUI', code1: 'PPP', code2: 'PPP', code3: 'PPP', code4: 'PPP', code5: 'PPP', code6: 'PPP', code7: 'PPP', code8: 'PPP', code9: 'PPP', code10: 'PPP'},
                {id: 'key8', code: 'YUI', code1: 'PPP', code2: 'PPP', code3: 'PPP', code4: 'PPP', code5: 'PPP', code6: 'PPP', code7: 'PPP', code8: 'PPP', code9: 'PPP', code10: 'PPP'},

              ],},
            {key: '2', tableName: '自治区国土局地质灾害易发分区信息_2', fields: [{name: 'id', label: '主键2', description: '无', type: '长整型', size: '20', ifKey: '是', ifNull: '是'},{name: 'code', label:  '地方基本编码', description: '无', type: '字符串型', size: '50', ifKey: '否', ifNull: '否'}],preview: [{id: 'key1', code: 'YUI'},{id: 'key2', code: 'YUI'},{id: 'key3', code: 'YUI'},{id: 'key4', code: 'YUI'},{id: 'key5', code: 'YUI'},],},
            {key: '3', tableName: '自治区国土局地质灾害易发分区信息_3', fields: [{name: 'id', label: '主键3', description: '无', type: '长整型', size: '18', ifKey: '是', ifNull: '否'},{name: 'code', label:  '地方基本编码', description: '无', type: '字符串型', size: '70', ifKey: '否', ifNull: '是'}],preview: [{id: 'key1', code: 'YUI'},{id: 'key2', code: 'YUI'},{id: 'key3', code: 'YUI'},{id: 'key4', code: 'YUI'},{id: 'key5', code: 'YUI'},],},
            {key: '4', tableName: '自治区国土局地质灾害易发分区信息_4', fields: [{name: 'id', label: '主键4', description: '无', type: '长整型', size: '18', ifKey: '是', ifNull: '否'},{name: 'code', label:  '地方基本编码', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '否'}],preview: [{id: 'key1', code: 'YUI'},{id: 'key2', code: 'YUI'},{id: 'key3', code: 'YUI'},{id: 'key4', code: 'YUI'},{id: 'key5', code: 'YUI'},],},
            {key: '5', tableName: '自治区国土局地质灾害易发分区信息_5', fields: [{name: 'id', label: '主键5', description: '无', type: '长整型', size: '20', ifKey: '是', ifNull: '否'},{name: 'code', label:  '地方基本编码', description: '无', type: '字符串型', size: '100', ifKey: '否', ifNull: '是'}],preview: [{id: 'key1', code: 'YUI'},{id: 'key2', code: 'YUI'},{id: 'key3', code: 'YUI'},{id: 'key4', code: 'YUI'},{id: 'key5', code: 'YUI'},],},
          ],
        },
        messages: [
          {id: '1', user: '2018L', createTime: '2018-09-11 20:10:22', content: '好评！'},
          {id: '2', user: '2018YYY', createTime: '2018-09-12 18:10:22', content: '好评!!!!!!!!!!!!!!!!!!!！'},
        ],
      },
      {
        id: '4',
        title: '党风廉政信息普查',
        subject: '市场监管，信用服务',
        rate: 2,
        key: '',
        authStatus: true,
        source: '自治区住建厅',
        dataFormat: '库表 文件 接口',
        sharedType: '有条件共享',
        openType: '不向社会开放',
        visitNum: 32,
        applyNum: 14,
        dataNum: 232,
        fileNum: 4,
        publishTime: '2018-07-04',
        updateFrequency: '每年',
        updateTime: '2018-07-04',
        star: false,
        description: '关于党风廉政普查信息',
        useCondition: {
          downloadNum: 5,
          ratePNum: 5,
          rateTNum: 3,
          rateNum: 5,
          rate: 2,
        },
        messageLength: 23,
        dataItem: [
          {name: '统一社会信用代码', format: '字符串型C', description: '统一社会信用代码'},
          {name: '主体名称', format: '字符串型C', description: '主体名称'},
          {name: '住所（经营场所）', format: '字符串型C', description: '住所（经营场所）'},
          {name: '经营者', format: '字符串型C', description: '经营者'},
          {name: '经营范围', format: '字符串型C', description: '经营范围'},
          {name: '经营期限起', format: '字符串型C', description: '经营期限起'},
          {name: '经营期限至', format: '字符串型C', description: '经营期限至'},
          {name: '成立日期', format: '字符串型C', description: '成立日期'},
        ],
        dataDetail: [
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
        ],
        folders: [{},{}],
        files: [
          { name: '大屏背景地球图.png', contentType: 'png', source: '网站上传', publishTime: '2018-09-09 12:21:25', size: '351kb', url: '/assets/地球.png'},
          { name: '自治区政务信息升级维护.pdf', contentType: 'pdf', source: '网站上传', publishTime: '2018-09-09 12:21:23', size: '321kb', url: '/documents/自治区政务信息共享网站建设和政务信息共享与交换平台升级维护FV.pdf'},
          { name: '地质灾害易发区.docx', contentType: 'docx', source: '网站上传', publishTime: '2018-09-09 12:21:25', size: '351kb', url: 'https://view.officeapps.live.com/op/view.aspx?src=newteach.pbworks.com%2Ff%2Fele%2Bnewsletter.docx'}
        ],
        messages: [
          {id: '1', user: '2018L', createTime: '2018-09-11 20:10:22', content: '好评！'},
          {id: '2', user: '2018YYY', createTime: '2018-09-12 18:10:22', content: '好评!!!!!!!!!!!!!!!!!!!！'},
        ],
      },
      {
        id: '5',
        title: '食品安全监督和管理',
        subject: '市场监管，信用服务',
        rate: 2,
        key: '',
        authStatus: true,
        source: '自治区质检局',
        dataFormat: '库表 文件 接口',
        sharedType: '有条件共享',
        openType: '不向社会开放',
        visitNum: 32,
        applyNum: 14,
        dataNum: 232,
        fileNum: 4,
        publishTime: '2018-07-04',
        updateFrequency: '每年',
        updateTime: '2018-07-04',
        star: false,
        description: '关于食品安全监督和管理信息',
        useCondition: {
          downloadNum: 5,
          ratePNum: 5,
          rateTNum: 3,
          rateNum: 5,
          rate: 2,
        },
        messageLength: 23,
        dataItem: [
          {name: '统一社会信用代码', format: '字符串型C', description: '统一社会信用代码'},
          {name: '主体名称', format: '字符串型C', description: '主体名称'},
          {name: '住所（经营场所）', format: '字符串型C', description: '住所（经营场所）'},
          {name: '经营者', format: '字符串型C', description: '经营者'},
          {name: '经营范围', format: '字符串型C', description: '经营范围'},
          {name: '经营期限起', format: '字符串型C', description: '经营期限起'},
          {name: '经营期限至', format: '字符串型C', description: '经营期限至'},
          {name: '成立日期', format: '字符串型C', description: '成立日期'},
        ],
        dataDetail: [
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: true},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
          {partition: '易发区', area: '4040234.35445043', show: false},
        ],
        interface: {
          url: '/sjw/gjxlmccxgjxlxx/1.3发分区信息',
          requestParams: [
            {name: 'ifkey', type: '字符串', require: '必填', description: '接口标识'},
            {name: 'query1', type: '字符串', require: '必填', description: '报表名称'},
            {name: 'query2', type: '字符串', require: '必填', description: '报表期别'},
            {name: 'tablename', type: '字符串', require: '必填', description: '业务数据实体表名'},
            {name: 'checkstr', type: '字符串', require: '必填', description: '有关部门提供的有效8位数校验码'},
          ],
          returnParams: [
            {name: 'set', description: '站点设置'},
            {name: 'type', description: '站点类型'},
            {name: 'run', description: '运行方向'},
          ],
          statusCode: [
            {code: '200', description: '请求成功'},
            {code: '201', description: '接口标识不正确'},
            {code: '202', description: '接口识别码不正确'},
            {code: '203', description: '无相关数据'},
            {code: '204', description: '当日查询字段超出'},
            {code: '205', description: '查询失败，请联系管理员'},
          ],
        },
        messages: [
          {id: '1', user: '2018L', createTime: '2018-09-11 20:10:22', content: '好评！'},
          {id: '2', user: '2018YYY', createTime: '2018-09-12 18:10:22', content: '好评!!!!!!!!!!!!!!!!!!!！'},
        ],
      },
    ],
  },
  effects: {
    * updateSubscription({ payload }, { call, put, select }) {
      const { data } = yield select(_ => _.sharedResource)
      yield put({
        type: 'save',
        payload: {
          data: data.map((item) => {
            if(item.id === payload.id) {
              item.star = !item.star;
            }
            return item;
          })
        }
      })
    },
  },
  reducers: {
    save(state, action) {
      return { ...state, ...action.payload };
    },
  },
};
