import { routerRedux } from 'dva/router';

export default {
  namespace: 'resourceUseManage',
  state: {
    ds_check: 'applyResource',
    authManage: {
      total: 6,
      wait: 4,
      accept: 1,
      reject: 1,
      data: [
        {
          id: '1',
          title: '地质灾害易发分区信息',
          status: 'wait', // wait, accept, reject,
          belongPlatform: '国家共享平台资源',
          requestUnit: '南宁市房管局',
          belongUnit: '自治区住建部',
          sharedProps: '无条件共享',
          createTime: '2018-07-04 11:43:12',
          updateTime: '2018-07-05 11:43:12',
          message: '',
          message2: '*已转发代理至国家共享平台，请耐心等待！',

          applicant: '广西壮族自治区住建部',
          apply_linkman: '李处长',
          apply_phone: '13980743229',
          apply_mail: '1234553@163.com',
          user_name: '南宁市房管局',
          use_linkman: '王主任',
          use_phone: '13780743328',
          use_mail: '3322344@qq.com',
          resource: '地质灾害易发分区信息',
          office_scene: '百城堵点',
          use_description: '行政依据',
          org: '系统业务',
          apply_basis: '依照相关政策法规进行使用申请',
          use_frequency: '20 次/天',
          use_date_scope: '工作日（8:00-18:00）',
          use_date_limit: '365天',
          other: '无',
          file: '无',
        },
        {
          id: '2',
          title: '地质灾害易发分区信息1',
          status: 'accept', // wait, accept, reject,
          belongPlatform: '自治区交换平台资源',
          requestUnit: '南宁市房管局',
          belongUnit: '自治区住建部',
          sharedProps: '无条件共享',
          createTime: '2018-07-04 11:43:12',
          updateTime: '2018-07-05 11:43:12',
          message: '*该资源为无条件授权资源，已自动授权。',

          applicant: '广西壮族自治区住建部',
          apply_linkman: '李处长',
          apply_phone: '13980743229',
          apply_mail: '1234553@163.com',
          user_name: '南宁市房管局',
          use_linkman: '王主任',
          use_phone: '13780743328',
          use_mail: '3322344@qq.com',
          resource: '地质灾害易发分区信息',
          office_scene: '百城堵点',
          use_description: '行政依据',
          org: '系统业务',
          apply_basis: '依照相关政策法规进行使用申请',
          use_frequency: '20 次/天',
          use_date_scope: '工作日（8:00-18:00）',
          use_date_limit: '365天',
          other: '无',
          file: '无',
        },
        {
          id: '3',
          title: '地质灾害易发分区信息1',
          status: 'reject', // wait, accept, reject,
          belongPlatform: '自治区交换平台资源',
          requestUnit: '南宁市房管局',
          belongUnit: '自治区住建部',
          sharedProps: '无条件共享',
          createTime: '2018-07-04 11:43:12',
          updateTime: '2018-07-05 11:43:12',
          message: '',

          applicant: '广西壮族自治区住建部',
          apply_linkman: '李处长',
          apply_phone: '13980743229',
          apply_mail: '1234553@163.com',
          user_name: '南宁市房管局',
          use_linkman: '王主任',
          use_phone: '13780743328',
          use_mail: '3322344@qq.com',
          resource: '地质灾害易发分区信息',
          office_scene: '百城堵点',
          use_description: '行政依据',
          org: '系统业务',
          apply_basis: '依照相关政策法规进行使用申请',
          use_frequency: '20 次/天',
          use_date_scope: '工作日（8:00-18:00）',
          use_date_limit: '365天',
          other: '无',
          file: '无',
        },
        {
          id: '4',
          title: '地质灾害易发分区信息1',
          status: 'wait', // wait, accept, reject,
          belongPlatform: '自治区交换平台资源',
          requestUnit: '南宁市房管局',
          belongUnit: '自治区住建部',
          sharedProps: '无条件共享',
          createTime: '2018-07-04 11:43:12',
          updateTime: '2018-07-05 11:43:12',
          message: '*请及时处理请求信息！',
          message2: '*提供方还未处理该资源，请耐心等待！',
          warning: 1,

          applicant: '广西壮族自治区住建部',
          apply_linkman: '李处长',
          apply_phone: '13980743229',
          apply_mail: '1234553@163.com',
          user_name: '南宁市房管局',
          use_linkman: '王主任',
          use_phone: '13780743328',
          use_mail: '3322344@qq.com',
          resource: '地质灾害易发分区信息',
          office_scene: '百城堵点',
          use_description: '行政依据',
          org: '系统业务',
          apply_basis: '依照相关政策法规进行使用申请',
          use_frequency: '20 次/天',
          use_date_scope: '工作日（8:00-18:00）',
          use_date_limit: '365天',
          other: '无',
          file: '无',
        },
        {
          id: '5',
          title: '地质灾害易发分区信息1',
          status: 'wait', // wait, accept, reject,
          belongPlatform: '自治区交换平台资源',
          requestUnit: '南宁市房管局',
          belongUnit: '自治区住建部',
          sharedProps: '无条件共享',
          createTime: '2018-07-04 11:43:12',
          updateTime: '2018-07-05 11:43:12',
          message: '*请及时处理请求信息！',
          message2: '*提供方还未处理该资源，请耐心等待！',
          warning: 2,

          applicant: '广西壮族自治区住建部',
          apply_linkman: '李处长',
          apply_phone: '13980743229',
          apply_mail: '1234553@163.com',
          user_name: '南宁市房管局',
          use_linkman: '王主任',
          use_phone: '13780743328',
          use_mail: '3322344@qq.com',
          resource: '地质灾害易发分区信息',
          office_scene: '百城堵点',
          use_description: '行政依据',
          org: '系统业务',
          apply_basis: '依照相关政策法规进行使用申请',
          use_frequency: '20 次/天',
          use_date_scope: '工作日（8:00-18:00）',
          use_date_limit: '365天',
          other: '无',
          file: '无',
        },
        {
          id: '6',
          title: '地质灾害易发分区信息1',
          status: 'wait', // wait, accept, reject,
          belongPlatform: '自治区交换平台资源',
          requestUnit: '南宁市房管局',
          belongUnit: '自治区住建部',
          sharedProps: '无条件共享',
          createTime: '2018-07-04 11:43:12',
          updateTime: '2018-07-05 11:43:12',
          message: '*请及时处理请求信息！',
          message2: '*提供方还未处理该资源，请耐心等待！',
          warning: 2,

          applicant: '广西壮族自治区住建部',
          apply_linkman: '李处长',
          apply_phone: '13980743229',
          apply_mail: '1234553@163.com',
          user_name: '南宁市房管局',
          use_linkman: '王主任',
          use_phone: '13780743328',
          use_mail: '3322344@qq.com',
          resource: '地质灾害易发分区信息',
          office_scene: '百城堵点',
          use_description: '行政依据',
          org: '系统业务',
          apply_basis: '依照相关政策法规进行使用申请',
          use_frequency: '20 次/天',
          use_date_scope: '工作日（8:00-18:00）',
          use_date_limit: '365天',
          other: '无',
          file: '无',
        },
      ],
    },

  },
  effects: {
    * updateSubscription({ payload }, { call, put, select }) {},
  },
  reducers: {
    save(state, action) {
      return { ...state, ...action.payload };
    },
  },
};
